#############################################################################
# Makefile for building: Gloomhaven.app/Contents/MacOS/Gloomhaven
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  Gloomhaven.pro
# Template: app
# Command: /usr/local/opt/qt/bin/qmake -o Makefile Gloomhaven.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/local/Cellar/qt/5.14.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.14.2/lib
QMAKE         = /usr/local/opt/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/opt/qt/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/opt/qt/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Gloomhaven1.0.0
DISTDIR = /Users/allen/Gloomhaven/.tmp/Gloomhaven1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.14.2/lib -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = action.cpp \
		character.cpp \
		characterdata.cpp \
		characterskill.cpp \
		gloomhaven.cpp \
		main.cpp \
		mainwindow.cpp \
		map.cpp \
		point.cpp \
		pregame.cpp qrc_image.cpp \
		moc_action.cpp \
		moc_characterdata.cpp \
		moc_characterskill.cpp \
		moc_mainwindow.cpp \
		moc_map.cpp \
		moc_point.cpp \
		moc_pregame.cpp
OBJECTS       = action.o \
		character.o \
		characterdata.o \
		characterskill.o \
		gloomhaven.o \
		main.o \
		mainwindow.o \
		map.o \
		point.o \
		pregame.o \
		qrc_image.o \
		moc_action.o \
		moc_characterdata.o \
		moc_characterskill.o \
		moc_mainwindow.o \
		moc_map.o \
		moc_point.o \
		moc_pregame.o
DIST          = /usr/local/Cellar/qt/5.14.2/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/lex.prf \
		Gloomhaven.pro action.h \
		character.h \
		characterdata.h \
		characterskill.h \
		gloomhaven.h \
		mainwindow.h \
		map.h \
		point.h \
		pregame.h action.cpp \
		character.cpp \
		characterdata.cpp \
		characterskill.cpp \
		gloomhaven.cpp \
		main.cpp \
		mainwindow.cpp \
		map.cpp \
		point.cpp \
		pregame.cpp
QMAKE_TARGET  = Gloomhaven
DESTDIR       = 
TARGET        = Gloomhaven.app/Contents/MacOS/Gloomhaven

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/allen/Gloomhaven/Gloomhaven.pro


include /usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Gloomhaven.app/Contents/MacOS/Gloomhaven:  $(OBJECTS)  
	@test -d Gloomhaven.app/Contents/MacOS/ || mkdir -p Gloomhaven.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Gloomhaven.pro /usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.14.2/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.14.2/mkspecs/features/lex.prf \
		Gloomhaven.pro \
		image.qrc \
		/usr/local/Cellar/qt/5.14.2/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile Gloomhaven.pro
/usr/local/Cellar/qt/5.14.2/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.14.2/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.14.2/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.14.2/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.14.2/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.14.2/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.14.2/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.14.2/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.14.2/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3drender.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3drender_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/resources_functions.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.14.2/mkspecs/features/lex.prf:
Gloomhaven.pro:
image.qrc:
/usr/local/Cellar/qt/5.14.2/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Gloomhaven.pro

qmake_all: FORCE

Gloomhaven.app/Contents/PkgInfo: 
	@test -d Gloomhaven.app/Contents || mkdir -p Gloomhaven.app/Contents
	@$(DEL_FILE) Gloomhaven.app/Contents/PkgInfo
	@echo "APPL????" > Gloomhaven.app/Contents/PkgInfo
Gloomhaven.app/Contents/Resources/empty.lproj: 
	@test -d Gloomhaven.app/Contents/Resources || mkdir -p Gloomhaven.app/Contents/Resources
	@touch Gloomhaven.app/Contents/Resources/empty.lproj
	
Gloomhaven.app/Contents/Info.plist: 
	@test -d Gloomhaven.app/Contents || mkdir -p Gloomhaven.app/Contents
	@$(DEL_FILE) Gloomhaven.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,weitung.Gloomhaven,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},weitung.Gloomhaven,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Gloomhaven,g" -e "s,@LIBRARY@,Gloomhaven,g" -e "s,\$${EXECUTABLE_NAME},Gloomhaven,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang/Info.plist.app >Gloomhaven.app/Contents/Info.plist

all: Makefile \
		Gloomhaven.app/Contents/PkgInfo \
		Gloomhaven.app/Contents/Resources/empty.lproj \
		Gloomhaven.app/Contents/Info.plist Gloomhaven.app/Contents/MacOS/Gloomhaven

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents image.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.14.2/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents action.h character.h characterdata.h characterskill.h gloomhaven.h mainwindow.h map.h point.h pregame.h $(DISTDIR)/
	$(COPY_FILE) --parents action.cpp character.cpp characterdata.cpp characterskill.cpp gloomhaven.cpp main.cpp mainwindow.cpp map.cpp point.cpp pregame.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Gloomhaven.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_image.cpp
qrc_image.cpp: image.qrc \
		/usr/local/Cellar/qt/5.14.2/bin/rcc \
		map_door.jpeg \
		map_floor_with_start.jpg \
		map_floor \
		monster1.txt \
		map1.txt \
		character1.txt
	/usr/local/Cellar/qt/5.14.2/bin/rcc -name image image.qrc -o qrc_image.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/5.14.2/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/Cellar/qt/5.14.2/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_action.cpp moc_characterdata.cpp moc_characterskill.cpp moc_mainwindow.cpp moc_map.cpp moc_point.cpp moc_pregame.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_action.cpp moc_characterdata.cpp moc_characterskill.cpp moc_mainwindow.cpp moc_map.cpp moc_point.cpp moc_pregame.cpp
moc_action.cpp: action.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.14.2/bin/moc
	/usr/local/Cellar/qt/5.14.2/bin/moc $(DEFINES) --include /Users/allen/Gloomhaven/moc_predefs.h -I/usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang -I/Users/allen/Gloomhaven -I/Users/allen/Gloomhaven -I/usr/local/Cellar/qt/5.14.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/usr/local/Cellar/qt/5.14.2/lib action.h -o moc_action.cpp

moc_characterdata.cpp: characterdata.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QDataStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qdatastream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		character.h \
		characterskill.h \
		action.h \
		point.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.14.2/bin/moc
	/usr/local/Cellar/qt/5.14.2/bin/moc $(DEFINES) --include /Users/allen/Gloomhaven/moc_predefs.h -I/usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang -I/Users/allen/Gloomhaven -I/Users/allen/Gloomhaven -I/usr/local/Cellar/qt/5.14.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/usr/local/Cellar/qt/5.14.2/lib characterdata.h -o moc_characterdata.cpp

moc_characterskill.cpp: characterskill.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QDataStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qdatastream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		action.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.14.2/bin/moc
	/usr/local/Cellar/qt/5.14.2/bin/moc $(DEFINES) --include /Users/allen/Gloomhaven/moc_predefs.h -I/usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang -I/Users/allen/Gloomhaven -I/Users/allen/Gloomhaven -I/usr/local/Cellar/qt/5.14.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/usr/local/Cellar/qt/5.14.2/lib characterskill.h -o moc_characterskill.cpp

moc_mainwindow.cpp: mainwindow.h \
		gloomhaven.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QDataStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qdatastream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		character.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		characterskill.h \
		action.h \
		point.h \
		characterdata.h \
		map.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.14.2/bin/moc
	/usr/local/Cellar/qt/5.14.2/bin/moc $(DEFINES) --include /Users/allen/Gloomhaven/moc_predefs.h -I/usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang -I/Users/allen/Gloomhaven -I/Users/allen/Gloomhaven -I/usr/local/Cellar/qt/5.14.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/usr/local/Cellar/qt/5.14.2/lib mainwindow.h -o moc_mainwindow.cpp

moc_map.cpp: map.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		point.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.14.2/bin/moc
	/usr/local/Cellar/qt/5.14.2/bin/moc $(DEFINES) --include /Users/allen/Gloomhaven/moc_predefs.h -I/usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang -I/Users/allen/Gloomhaven -I/Users/allen/Gloomhaven -I/usr/local/Cellar/qt/5.14.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/usr/local/Cellar/qt/5.14.2/lib map.h -o moc_map.cpp

moc_point.cpp: point.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.14.2/bin/moc
	/usr/local/Cellar/qt/5.14.2/bin/moc $(DEFINES) --include /Users/allen/Gloomhaven/moc_predefs.h -I/usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang -I/Users/allen/Gloomhaven -I/Users/allen/Gloomhaven -I/usr/local/Cellar/qt/5.14.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/usr/local/Cellar/qt/5.14.2/lib point.h -o moc_point.cpp

moc_pregame.cpp: pregame.h \
		gloomhaven.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QDataStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qdatastream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		character.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		characterskill.h \
		action.h \
		point.h \
		characterdata.h \
		map.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.14.2/bin/moc
	/usr/local/Cellar/qt/5.14.2/bin/moc $(DEFINES) --include /Users/allen/Gloomhaven/moc_predefs.h -I/usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang -I/Users/allen/Gloomhaven -I/Users/allen/Gloomhaven -I/usr/local/Cellar/qt/5.14.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/usr/local/Cellar/qt/5.14.2/lib pregame.h -o moc_pregame.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

action.o: action.cpp action.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o action.o action.cpp

character.o: character.cpp character.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QDataStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qdatastream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		characterskill.h \
		action.h \
		point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o character.o character.cpp

characterdata.o: characterdata.cpp characterdata.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QDataStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qdatastream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		character.h \
		characterskill.h \
		action.h \
		point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o characterdata.o characterdata.cpp

characterskill.o: characterskill.cpp characterskill.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QDataStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qdatastream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		action.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o characterskill.o characterskill.cpp

gloomhaven.o: gloomhaven.cpp gloomhaven.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QDataStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qdatastream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		character.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		characterskill.h \
		action.h \
		point.h \
		characterdata.h \
		map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gloomhaven.o gloomhaven.cpp

main.o: main.cpp mainwindow.h \
		gloomhaven.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QDataStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qdatastream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		character.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		characterskill.h \
		action.h \
		point.h \
		characterdata.h \
		map.h \
		pregame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		gloomhaven.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QDataStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qdatastream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		character.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		characterskill.h \
		action.h \
		point.h \
		characterdata.h \
		map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

map.o: map.cpp map.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o map.o map.cpp

point.o: point.cpp point.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point.o point.cpp

pregame.o: pregame.cpp pregame.h \
		gloomhaven.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QDataStream \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qdatastream.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qstring.h \
		character.h \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers/qobject.h \
		characterskill.h \
		action.h \
		point.h \
		characterdata.h \
		map.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pregame.o pregame.cpp

qrc_image.o: qrc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_image.o qrc_image.cpp

moc_action.o: moc_action.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_action.o moc_action.cpp

moc_characterdata.o: moc_characterdata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_characterdata.o moc_characterdata.cpp

moc_characterskill.o: moc_characterskill.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_characterskill.o moc_characterskill.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_map.o: moc_map.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_map.o moc_map.cpp

moc_point.o: moc_point.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_point.o moc_point.cpp

moc_pregame.o: moc_pregame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pregame.o moc_pregame.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

